### ISSUE TITLE
Lots of missing symbols.

### ISSUE THREAD

**Issue by holdengreen** [gecko0307/bindbc-wgpu#15]
When I try to run my code which just uses this library to instantiate an SDL window and a wgpu surface with xlib,
webgpu does not initialize other then as a 'badLibrary'.

Instead there are many loader errors referring to 'Missing Symbol'(s).

I try passing a libwgpu.so that I get from [here](https://github.com/gfx-rs/wgpu-native/releases).
But it is the same.

**Comment by holdengreen** [comment]
Specifically here is the output:

```
Missing Symbol: wgpuCreateInstance
Missing Symbol: wgpuGetProcAddress
Missing Symbol: wgpuAdapterEnumerateFeatures
Missing Symbol: wgpuAdapterHasFeature
Missing Symbol: wgpuBufferGetConstMappedRange
Missing Symbol: wgpuCommandEncoderFillBuffer
Missing Symbol: wgpuCommandEncoderInsertDebugMarker
Missing Symbol: wgpuCommandEncoderPopDebugGroup
Missing Symbol: wgpuCommandEncoderPushDebugGroup
Missing Symbol: wgpuCommandEncoderResolveQuerySet
Missing Symbol: wgpuCommandEncoderWriteTimestamp
Missing Symbol: wgpuComputePassEncoderBeginPipelineStatisticsQuery
Missing Symbol: wgpuComputePassEncoderEndPipelineStatisticsQuery
Missing Symbol: wgpuComputePassEncoderInsertDebugMarker
Missing Symbol: wgpuComputePassEncoderPopDebugGroup
Missing Symbol: wgpuComputePassEncoderPushDebugGroup
Missing Symbol: wgpuComputePipelineGetBindGroupLayout
Missing Symbol: wgpuComputePipelineSetLabel
Missing Symbol: wgpuDeviceCreateComputePipelineAsync
Missing Symbol: wgpuDeviceCreateQuerySet
Missing Symbol: wgpuDeviceCreateRenderBundleEncoder
Missing Symbol: wgpuDeviceCreateRenderPipelineAsync
Missing Symbol: wgpuDeviceDestroy
Missing Symbol: wgpuDeviceEnumerateFeatures
Missing Symbol: wgpuDeviceHasFeature
Missing Symbol: wgpuDevicePopErrorScope
Missing Symbol: wgpuDevicePushErrorScope
Missing Symbol: wgpuDeviceSetDeviceLostCallback
Missing Symbol: wgpuDeviceSetUncapturedErrorCallback
Missing Symbol: wgpuInstanceProcessEvents
Missing Symbol: wgpuQuerySetDestroy
Missing Symbol: wgpuQueueOnSubmittedWorkDone
Missing Symbol: wgpuRenderBundleEncoderDraw
Missing Symbol: wgpuRenderBundleEncoderDrawIndexed
Missing Symbol: wgpuRenderBundleEncoderDrawIndexedIndirect
Missing Symbol: wgpuRenderBundleEncoderDrawIndirect
Missing Symbol: wgpuRenderBundleEncoderFinish
Missing Symbol: wgpuRenderBundleEncoderInsertDebugMarker
Missing Symbol: wgpuRenderBundleEncoderPopDebugGroup
Missing Symbol: wgpuRenderBundleEncoderPushDebugGroup
Missing Symbol: wgpuRenderBundleEncoderSetBindGroup
Missing Symbol: wgpuRenderBundleEncoderSetIndexBuffer
Missing Symbol: wgpuRenderBundleEncoderSetPipeline
Missing Symbol: wgpuRenderBundleEncoderSetVertexBuffer
Missing Symbol: wgpuRenderPassEncoderBeginOcclusionQuery
Missing Symbol: wgpuRenderPassEncoderBeginPipelineStatisticsQuery
Missing Symbol: wgpuRenderPassEncoderEndOcclusionQuery
Missing Symbol: wgpuRenderPassEncoderEndPipelineStatisticsQuery
Missing Symbol: wgpuRenderPassEncoderExecuteBundles
Missing Symbol: wgpuRenderPassEncoderInsertDebugMarker
Missing Symbol: wgpuRenderPassEncoderPopDebugGroup
Missing Symbol: wgpuRenderPassEncoderPushDebugGroup
Missing Symbol: wgpuRenderPipelineGetBindGroupLayout
Missing Symbol: wgpuRenderPipelineSetLabel
Missing Symbol: wgpuShaderModuleGetCompilationInfo
Missing Symbol: wgpuShaderModuleSetLabel
```

It could be a versioning issue...

**Comment by holdengreen** [comment]
Had to change "targetName": "demo" -> "targetName": "demo.bin" since it couldn't delete the 'demo' directory.

The demo project has this exact same issue...

(I'm on Manjaro... Should I try running this is a different environment?)

**Comment by gecko0307** [comment]
This is ok, these functions are not present in wgpu 0.11.0. The triangle demo (`dub build --config=demo`) should work despite loading as "badLibrary".
The binding needs an update to 0.12.0, though.

**Comment by holdengreen** [comment]
Ok then...
SDL is opening a window, but returning `SDL_SYSWM_UNKNOWN` and not really working...

But I'm going to create a guix container and see how it goes and see if there is real issue.

**Comment by gecko0307** [comment]
Actually I didn't test the example on systems other than Windows, so it's quite possible that there are some issues. `SDL_SYSWM_UNKNOWN` hints that it can be SDL bug or unsupported platform.

**Comment by holdengreen** [comment]
Thanks its likely an issue/exotic configuration with my system.
For reference I'm on Manjaro, running XFCE with `nvidia-xrun`,
and with a lot of crust.
C libraries using SDL, or GLFW work,
but these new languages like D and Rust have been failing to instantiate windows.

Once I'm done setting up my Debian development (I call it devian) VM I will test.
And also a Guix VM.

**Comment by holdengreen** [comment]
How should I go about updating this and trying to get it to work myself?
I want to use D for my project (not Rust).

**Comment by gecko0307** [comment]
Closing the issue. All the missing functions are now available.
