### ISSUE TITLE
`wgpu_compute_pipeline_destroy` is not bound

### ISSUE THREAD

**Issue by chances** [gecko0307/bindbc-wgpu#7]
Defined in [`wgpu.h` at line 2023](https://github.com/gecko0307/bindbc-wgpu/blob/918a8721a7ce7fb341b52f26fd72744e43e8c3b2/wgpu.h#L2023).

**Comment by gecko0307** [comment]
Thanks for pointing out! There should be a way to generate function declarations automatically to prevent such bugs, but I haven't come up with a solution yet. htod doesn't work correctly with `wgpu.h`, so probably such generator should run on Rust side.
